[package]
name = "aoc-2022-day-16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"

[[bin]]
name = "aoc-2022-day-16"
path = "main.rs"
