[package]
name = "aoc-2023-7"
version = "1.74.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "aoc-2023-7"
path = "main.rs"
