[package]
name = "aoc-2022-day-24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.14.3"

[[bin]]
name = "aoc-2022-day-24"
path = "main.rs"
