[package]
name = "aoc-2018-19"
version = "1.84.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }

[[bin]]
name = "aoc-2018-19"
path = "main.rs"
