[package]
name = "aoc-2024-13"
version = "1.84.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = {version="0.12.1", features = ["static-link-z3"]}

[[bin]]
name = "aoc-2024-13"
path = "main.rs"
